Set texlive arch depending on architecture

diff --git a/alpine/latex/Dockerfile b/alpine/latex/Dockerfile
--- a/alpine/latex/Dockerfile
+++ b/alpine/latex/Dockerfile
@@ -13,16 +13,13 @@ RUN apk --no-cache add \
         wget \
         xz
 
-# TeXLive binaries location
-ARG texlive_bin="/opt/texlive/texdir/bin"
-
-# Modify PATH environment variable, prepending TexLive bin directory
-ENV PATH="${texlive_bin}/default:${PATH}"
-
 # Installer scripts and config
 COPY common/latex/texlive.profile    /root/texlive.profile
 COPY common/latex/install-texlive.sh /root/install-texlive.sh
 COPY common/latex/packages.txt       /root/packages.txt
+
+# TeXLive binaries location
+ARG texlive_bin="/opt/texlive/texdir/bin"
 
 # TeXLive version to install (leave empty to use the latest version).
 ARG texlive_version=
@@ -30,11 +27,24 @@ ARG texlive_version=
 # TeXLive mirror URL (leave empty to use the default mirror).
 ARG texlive_mirror_url=
 
+# Modify PATH environment variable, prepending TexLive bin directory
+ENV PATH="${texlive_bin}/default:${PATH}"
+
 # The architecture suffix may vary based on different distributions,
 # particularly for musl libc based distrubions, like Alpine linux,
 # where the suffix is linuxmusl
 RUN ARCH="$(uname -m)" && \
-    TEXLIVE_ARCH="${ARCH}-linuxmusl" && \
+    case "$ARCH" in \
+        ('aarch64') \
+            TEXLIVE_ARCH="binary-aarch64-linux"; \
+            ;; \
+        ('x86_64') \
+            TEXLIVE_ARCH="binary-x86_64-linuxmusl"; \
+            ;; \
+        (*) echo >&2 "error: unsupported architecture '$ARCH'"; \
+            exit 1 \
+            ;; \
+    esac && \
     mkdir -p ${texlive_bin} && \
     ln -sf "${texlive_bin}/${TEXLIVE_ARCH}" "${texlive_bin}/default" && \
 # Request musl precompiled binary access
