Cleanup LaTeX builds

diff --git a/alpine/latex/Dockerfile b/alpine/latex/Dockerfile
--- a/alpine/latex/Dockerfile
+++ b/alpine/latex/Dockerfile
@@ -19,25 +19,13 @@ RUN apk --no-cache add \
         wget \
         xz
 
+# Installer scripts and config
+COPY common/latex/texlive.profile    /root/texlive.profile
+COPY common/latex/install-texlive.sh /root/install-texlive.sh
+COPY common/latex/packages.txt       /root/packages.txt
+
 # TeXLive binaries location
 ARG texlive_bin="/opt/texlive/texdir/bin"
-
-# The architecture suffix may vary based on different distributions,
-# particularly for musl libc based distrubions, like Alpine linux,
-# where the suffix is linuxmusl
-RUN TEXLIVE_ARCH="$(uname -m)-linuxmusl" && \
-    mkdir -p ${texlive_bin} && \
-    ln -sf "${texlive_bin}/${TEXLIVE_ARCH}" "${texlive_bin}/default"
-
-# Modify PATH environment variable, prepending TexLive bin directory
-ENV PATH="${texlive_bin}/default:${PATH}"
-
-WORKDIR /root
-
-# Installer scripts and config
-COPY common/latex/texlive.profile /root/texlive.profile
-COPY common/latex/install-texlive.sh /root/install-texlive.sh
-COPY common/latex/packages.txt /root/packages.txt
 
 # TeXLive version to install (leave empty to use the latest version).
 ARG texlive_version=
@@ -45,18 +33,37 @@ ARG texlive_version=
 # TeXLive mirror URL (leave empty to use the default mirror).
 ARG texlive_mirror_url=
 
+# Modify PATH environment variable, prepending TexLive bin directory
+ENV PATH="${texlive_bin}/default:${PATH}"
+
+# Ideally, the image would always install "linuxmusl" binaries. However,
+# those are not available for aarch64, so we install binaries that have
+# been built against libc and hope that the compatibility layer works
+# well enough.
+RUN cd /root && \
+    ARCH="$(uname -m)" && \
+    case "$ARCH" in \
+        ('x86_64') \
+            TEXLIVE_ARCH="x86_64-linuxmusl"; \
+            ;; \
+        (*) echo >&2 "error: unsupported architecture '$ARCH'"; \
+            exit 1 \
+            ;; \
+    esac && \
+    mkdir -p ${texlive_bin} && \
+    ln -sf "${texlive_bin}/${TEXLIVE_ARCH}" "${texlive_bin}/default" && \
 # Request musl precompiled binary access
-RUN echo "binary_x86_64-linuxmusl 1" >> /root/texlive.profile \
-  && ( \
+    echo "binary_${TEXLIVE_ARCH} 1" >> /root/texlive.profile && \
+    ( \
      [ -z "$texlive_version"    ] || printf '-t\n%s\n"' "$texlive_version"; \
      [ -z "$texlive_mirror_url" ] || printf '-m\n%s\n' "$texlive_mirror_url" \
-     ) | xargs /root/install-texlive.sh \
-  && sed -e 's/ *#.*$//' -e '/^ *$/d' /root/packages.txt | \
-     xargs tlmgr install \
-  && rm -f /root/texlive.profile \
-           /root/install-texlive.sh \
-           /root/packages.txt \
-  && TERM=dumb luaotfload-tool --update \
-  && chmod -R o+w /opt/texlive/texdir/texmf-var
+    ) | xargs /root/install-texlive.sh && \
+    sed -e 's/ *#.*$//' -e '/^ *$/d' /root/packages.txt | \
+        xargs tlmgr install && \
+    rm -f /root/texlive.profile \
+          /root/install-texlive.sh \
+          /root/packages.txt && \
+    TERM=dumb luaotfload-tool --update && \
+    chmod -R o+w /opt/texlive/texdir/texmf-var
 
 WORKDIR /data
